#ifndef __INCLUDED_USELESS_TEMPLATE_CONFIG_H__
#define __INCLUDED_USELESS_TEMPLATE_CONFIG_H__

#ifdef TEMPLATES_MSVC100
#   define USELESS_EMPTY_SPECIALIZATION
#   define USELESS_SPECIALIZATION template<>
#	define USELESS_CONSTRUCTOR_SPECIALIZATION
#   define USELESS_TYPENAME typename
#   define USELESS_STRUCT struct
#elif defined(TEMPLATES_MSVC70)
#   define USELESS_EMPTY_SPECIALIZATION
#   define USELESS_SPECIALIZATION template<>
#	define USELESS_CONSTRUCTOR_SPECIALIZATION
#   define USELESS_TYPENAME typename
#   define USELESS_STRUCT
#elif defined(TEMPLATES_GCC29)
#   define USELESS_EMPTY_SPECIALIZATION
#   define USELESS_SPECIALIZATION
#   define USELESS_CONSTRUCTOR_SPECIALIZATION
#   define USELESS_TYPENAME typename
#   define USELESS_STRUCT struct
#else
#   error You must define in the project one of: TEMPLATES_GCC29, TEMPLATES_MSVC70, TEMPLATES_MSVC100!!!

#endif

#endif//__INCLUDED_USELESS_TEMPLATE_CONFIG_H__
